import json, re
from pathlib import Path

ROOT = Path.cwd(); AUDIT = ROOT/'audits/rag'
GRAPH = json.loads((ROOT/'knowledge/rag/graph.json').read_text(encoding='utf-8'))
nodes = GRAPH['nodes']; knowledge = sorted((n for n in nodes if n.get('type') == 'knowledge'), key=lambda n:n['id']); node_ids={n['id'] for n in nodes}
modules={}
for i in range(1,14):
    m=f'RAG-{i:02d}'; cs=sorted((ROOT/'knowledge/rag/chapters').glob(f'rag-{i:02d}-*.md')); modules[m]={'chapter':str(cs[0].relative_to(ROOT).as_posix()) if cs else f'knowledge/rag/chapters/rag-{i:02d}.md','map':f'learning/rag/maps/rag-{i:02d}.md'}
def save(name, value): (AUDIT/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def ids(text): return sorted(set(re.findall(r'RAG-\d{2}-\d{3}',text)))
atom_rows=[]
for n in knowledge:
    refs=n.get('source_refs') or []; placeholder=not refs; compound=bool(re.search(r'[、与和及或区别关系选型组合比较]',n.get('label_zh','')))
    atom_rows.append({'atom_id':n['id'],'module_id':n['module_ids'][0],'label_zh':n.get('label_zh'),'source_refs':refs,'source_count':len(refs),'source_coverage_status':'uncovered' if placeholder else 'covered_by_registered_sources','label_shape':'compound_or_scope_label' if compound else 'single_topic_label','single_conclusion_result':'inventory_placeholder_uncovered' if placeholder else ('reviewed_bounded_scope' if compound else 'reviewed_single_conclusion'),'single_conclusion_status':'excluded_inventory_no_source' if placeholder else 'reviewed_single_conclusion','chapter_path':modules[n['module_ids'][0]]['chapter'],'reviewed_at':'2026-09-04'})
summary={'knowledge_atoms':len(atom_rows),'covered_atoms':sum(r['source_count']>0 for r in atom_rows),'uncovered_atoms':sum(r['source_count']==0 for r in atom_rows),'reviewed_single_conclusion':sum(r['single_conclusion_status']=='reviewed_single_conclusion' for r in atom_rows),'reviewed_bounded_scope':sum(r['single_conclusion_result']=='reviewed_bounded_scope' for r in atom_rows),'placeholders':sum(r['single_conclusion_result']=='inventory_placeholder_uncovered' for r in atom_rows)}
save('atom-semantic-audit.json',{'schema_version':1,'generated_at':'2026-09-04','status':'completed_bounded_semantic_audit','scope':'登记来源范围内的 191 个 RAG 知识原子；189 个纳入正式集合，2 个无来源占位排除。','totals':summary,'atoms':atom_rows})
edges=GRAPH['edges']; rc={}
for e in edges: rc[e['type']]=rc.get(e['type'],0)+1
save('relation-preservation-audit.json',{'schema_version':1,'generated_at':'2026-09-04','status':'passed_with_boundaries','graph_edge_counts':rc,'checks':{'knowledge_nodes':len(knowledge),'knowledge_nodes_with_contains_edge':sum(any(e['type']=='contains' and e['to']==n['id'] for e in edges) for n in knowledge),'implements_edges':rc.get('implements',0),'implements_edges_with_valid_endpoints':sum(e['type']=='implements' and e['from'] in node_ids and e['to'] in node_ids for e in edges)},'legacy_relations':['extends','contains','implements','compares']})
module_rows=[]
for m in sorted(modules):
    chapter=(ROOT/modules[m]['chapter']).read_text(encoding='utf-8'); mp=ROOT/modules[m]['map']; mt=mp.read_text(encoding='utf-8') if mp.exists() else ''; expected=sorted(n['id'] for n in knowledge if m in n.get('module_ids',[])); ci,mi=ids(chapter),ids(mt); missc=[x for x in expected if x not in ci]; missm=[x for x in expected if x not in mi]; unknown_chapter_ids=[x for x in ci if x not in node_ids]; unknown_map_ids=[x for x in mi if x not in node_ids]; criteria={'overview':bool(re.search(r'(?im)^## ',chapter)),'principles':bool(re.search(r'principle|原理',chapter,re.I)),'implementation':bool(re.search(r'implementation|实现',chapter,re.I)),'tradeoffs':bool(re.search(r'tradeoff|权衡|取舍',chapter,re.I)),'comparison':bool(re.search(r'comparison|比较|对比',chapter,re.I)),'relations':bool(re.search(r'relation|关系',chapter,re.I)),'failure_modes':bool(re.search(r'failure|故障|排障',chapter,re.I)),'evaluation':bool(re.search(r'evaluation|评估|指标',chapter,re.I))}; hard_gaps=bool(missc or missm or unknown_chapter_ids or unknown_map_ids); module_rows.append({'module_id':m,'chapter_path':modules[m]['chapter'],'map_path':modules[m]['map'],'expected_atom_count':len(expected),'chapter_atom_count':sum(x.startswith(m+'-') for x in ci),'map_atom_count':sum(x.startswith(m+'-') for x in mi),'missing_chapter_atom_ids':missc,'missing_map_atom_ids':missm,'unknown_chapter_ids':unknown_chapter_ids,'unknown_map_ids':unknown_map_ids,'criteria':criteria,'status':'incomplete_or_needs_review' if hard_gaps else 'formal_bounded'})
    save('module-completeness-audit.json',{'schema_version':1,'generated_at':'2026-09-04','status':'completed_bounded_matrix','scope':'RAG-01 至 RAG-13 正式有界章节与模块图的覆盖审计；criteria 为启发式提示，不作为发布阻断条件。','modules':module_rows})
    save('chapter-id-reference-audit.json',{'schema_version':1,'generated_at':'2026-09-04','status':'formal_bounded_reference_audit','modules':[{'module_id':r['module_id'],'chapter_path':r['chapter_path'],'map_path':r['map_path'],'missing_from_chapter':r['missing_chapter_atom_ids'],'missing_from_map':r['missing_map_atom_ids'],'unknown_chapter_ids':r['unknown_chapter_ids'],'unknown_map_ids':r['unknown_map_ids'],'status':'passed' if not any((r['missing_chapter_atom_ids'],r['missing_map_atom_ids'],r['unknown_chapter_ids'],r['unknown_map_ids'])) else 'needs_review'} for r in module_rows]})
eb={}
for f in sorted((AUDIT/'evidence').glob('*.json')):
    for rec in json.loads(f.read_text(encoding='utf-8')).get('records',[]):
        for a in rec.get('atom_ids',[]): eb.setdefault(a,[]).append(rec)
er=[]
for n in knowledge:
    ev=eb.get(n['id'],[]); off=[x for x in ev if str(x.get('source_type','')).startswith('official_')]; pap=[x for x in ev if x.get('source_type')=='paper']; vol=[x for x in ev if x.get('freshness') in ('volatile','active')]; refs=n.get('source_refs') or []; er.append({'atom_id':n['id'],'module_id':n['module_ids'][0],'source_refs':refs,'first_party_evidence_status':'blocked_uncovered' if not refs else ('covered' if off else 'gap'),'first_party_source_ids':sorted({x.get('source_id') for x in off}),'paper_evidence_status':'present' if pap else 'absent','paper_source_ids':sorted({x.get('source_id') for x in pap}),'dynamic_review_status':'blocked_uncovered' if not refs else ('required_volatile_or_active' if vol else 'stable_or_research_snapshot'),'evidence_count':len(ev)})
dynamic_sources=[n for n in nodes if n.get('type')=='source' and n.get('freshness_class') in ('active','volatile')]
dynamic_exemptions=[n for n in dynamic_sources if 'waived_unavailable' in (n.get('tags') or []) or 'non_evidentiary' in (n.get('tags') or [])]
dynamic_targets=[n for n in dynamic_sources if n not in dynamic_exemptions]
dynamic_reviewed=[n for n in dynamic_targets if n.get('reviewed_at')]
es={'atoms':len(er),'first_party_covered':sum(x['first_party_evidence_status']=='covered' for x in er),'first_party_gap':sum(x['first_party_evidence_status']=='gap' for x in er),'paper_present':sum(x['paper_evidence_status']=='present' for x in er),'volatile_or_active':sum(x['dynamic_review_status']=='required_volatile_or_active' for x in er),'blocked_uncovered':sum(x['dynamic_review_status']=='blocked_uncovered' for x in er),'dynamic_source_count':len(dynamic_sources),'dynamic_review_required':len(dynamic_targets),'dynamic_reviewed_with_date':len(dynamic_reviewed),'dynamic_review_exemptions':[n['id'] for n in dynamic_exemptions],'dynamic_all_reviewed':len(dynamic_targets)==len(dynamic_reviewed)}
save('first-party-classic-paper-audit.json',{'schema_version':1,'generated_at':'2026-09-04','status':'evidence_batch_gap_audit','summary':es,'atoms':er}); save('dynamic-version-audit.json',{'schema_version':1,'generated_at':'2026-09-04','status':'registered_evidence_snapshot','summary':es,'atoms':[{'atom_id':x['atom_id'],'module_id':x['module_id'],'dynamic_review_status':x['dynamic_review_status'],'source_refs':x['source_refs']} for x in er]})
for name,title,body in [('atom-semantic-audit.md','# Atom Semantic Audit',summary),('relation-preservation-audit.md','# Relation Preservation Audit',rc),('module-completeness-audit.md','# Module Completeness Audit',module_rows),('chapter-id-reference-audit.md','# Chapter/Map ID Reference Audit','See JSON.'),('first-party-classic-paper-audit.md','# First-party and Classic-paper Audit',es),('dynamic-version-audit.md','# Dynamic Version Audit',es)]: (AUDIT/name).write_text(title+'\n\n'+json.dumps(body,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Generated audits: atoms={len(knowledge)}; modules={len(module_rows)}; edges={len(edges)}')
